### ISSUE TITLE
refactor easings

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/axis-www#4]
I might be wrong here, but wouldn't it be easier to pass a list of supported easings to both stylus and jade and render out all the entries instead of writing them down? Like this, we could reduce some redundancy.

I have to know first though, is there a way to pass variables to both stylus and jade from a shared settings file?

**Comment by jenius** [comment]
Not really, unfortunately :confused:

**Comment by FranzSkuffka** [comment]
A roots plugin would do that, wouldn't it?

**Comment by jenius** [comment]
For this tiny use case, way too much effort

**Comment by FranzSkuffka** [comment]
Wanted to take a shot a creating one anyways.
I'll keep you posted.
