### ISSUE TITLE
Axis version used in the docs is not up to date.

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/axis-www#6]
Swift easings do not work.

**Comment by dbox** [comment]
I did a new npm install of axis which updated it to ` "axis": "^0.3.1",` but didn't seem to fix it.

**Comment by FranzSkuffka** [comment]
the actual axis version containing the swift easings is not published yet.

**Comment by jenius** [comment]
Yeah sorry that wasn't yet published. This should have been logged in axis really but it's ok, fixed now and published!

**Comment by dbox** [comment]
So should swift easing be working here? http://axis.netlify.com/#easing or something still needs to be published?

**Comment by FranzSkuffka** [comment]
I think the docs need to be republished.

**Comment by dbox** [comment]
Yeah works locally for me now. Maybe the build failed when publishing to netlify (or bitballoon, whichever is the correct one now)

**Comment by jenius** [comment]
Yeah seems like it's a netlify issue. Trying a re-trigger now

**Comment by FranzSkuffka** [comment]
Did not work out i think.

**Comment by FranzSkuffka** [comment]
i think axis the new axis version has not been published yet because it does _not_ work locally for me.

**Comment by dbox** [comment]
Weird, works locally for me, and I thought it was working on the web as well. 

Regardless, axis is awaiting a few PRs and already needs a version-up, so whenver that happens should be all good.

@jenius is traveling and has been out of pocket for a bit now

**Comment by jenius** [comment]
Hey guys, yup I've been off the grid for a couple weeks in the countryside without internets. Back now and will make sure things are more caught up.
